In [1]:
from statsbombpy import sb

In [12]:
competition_data = sb.competitions()
print(competition_data[60:65])

    competition_id  season_id              country_name competition_name  \
60              49          3  United States of America             NWSL
61               2         27                   England   Premier League
62               2         44                   England   Premier League
63              12         27                     Italy          Serie A
64              12         86                     Italy          Serie A

   competition_gender  competition_youth  competition_international  \
60             female              False                      False
61               male              False                      False
62               male              False                      False
63               male              False                      False
64               male              False                      False

   season_name               match_updated        match_updated_360  \
60        2018  2023-07-24T13:01:22.094587  2021-06-13T16:17:31.694
61   2015/2016  2023-11-14T11:25:33.476498  2021-06-13T16:17:31.694
62   2003/2004  2023-11-14T11:20:59.843499  2021-06-13T16:17:31.694
63   2015/2016  2023-12-13T17:32:46.423081                     None
64   1986/1987  2023-06-18T01:55:53.343752                     None

   match_available_360             match_available
60                None  2023-07-24T13:01:22.094587
61                None  2023-11-14T11:25:33.476498
62                None  2023-11-14T11:20:59.843499
63                None  2023-12-13T17:32:46.423081
64                None  2023-06-18T01:55:53.343752

D:\jupyter\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [56]:
match = sb.matches(competition_id=2, season_id=27)
print(match[365:370])

     match_id  match_date      kick_off               competition     season  \
365   3754338  2016-01-16  16:00:00.000  England - Premier League  2015/2016
366   3754340  2016-02-02  21:00:00.000  England - Premier League  2015/2016
367   3754341  2016-01-23  16:00:00.000  England - Premier League  2015/2016
368   3754342  2016-05-08  17:00:00.000  England - Premier League  2015/2016
369   3754345  2016-01-17  15:05:00.000  England - Premier League  2015/2016

                home_team          away_team  home_score  away_score  \
365      Newcastle United    West Ham United           2           1
366  West Bromwich Albion       Swansea City           1           1
367        Leicester City         Stoke City           3           0
368             Liverpool            Watford           2           0
369             Liverpool  Manchester United           0           1

    match_status  ...         last_updated_360 match_week competition_stage  \
365    available  ...  2021-06-12T16:17:31.694         22    Regular Season
366    available  ...  2021-06-12T16:17:31.694         24    Regular Season
367    available  ...  2021-06-12T16:17:31.694         23    Regular Season
368    available  ...  2021-06-12T16:17:31.694         37    Regular Season
369    available  ...  2021-06-12T16:17:31.694         22    Regular Season

                 stadium           referee    home_managers  \
365     St. James'' Park    Neil Swarbrick   Steve McClaren
366        The Hawthorns    Neil Swarbrick       Tony Pulis
367  King Power Stadium          Mike Dean  Claudio Ranieri
368             Anfield          Lee Mason     Jürgen Klopp
369             Anfield   Mark Clattenburg     Jürgen Klopp

              away_managers data_version shot_fidelity_version  \
365            Slaven Bilić        1.1.0                     2
366      Francesco Guidolin        1.1.0                     2
367             Mark Hughes        1.1.0                     2
368  Enrique Sánchez Flores        1.1.0                     2
369          Louis van Gaal        1.1.0                     2

    xy_fidelity_version
365                   2
366                   2
367                   2
368                   2
369                   2

[5 rows x 22 columns]

D:\jupyter\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [57]:
events = sb.events(match_id=3754345)

D:\jupyter\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [58]:
events.head()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,...,shot_technique,shot_type,substitution_outcome,substitution_replacement,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Liverpool,24,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Manchester United,39,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Manchester United,39,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Liverpool,24,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Manchester United,39,00:00:00.000,Half Start,NaN

In [59]:
events.columns

Index(['50_50', 'ball_receipt_outcome', 'ball_recovery_recovery_failure',
       'carry_end_location', 'clearance_aerial_won', 'clearance_body_part',
       'clearance_head', 'clearance_left_foot', 'clearance_right_foot',
       'counterpress', 'dribble_outcome', 'duel_outcome', 'duel_type',
       'duration', 'foul_committed_advantage', 'foul_committed_card',
       'foul_committed_offensive', 'foul_committed_type', 'foul_won_advantage',
       'foul_won_defensive', 'goalkeeper_body_part', 'goalkeeper_end_location',
       'goalkeeper_outcome', 'goalkeeper_position', 'goalkeeper_technique',
       'goalkeeper_type', 'id', 'index', 'interception_outcome', 'location',
       'match_id', 'minute', 'miscontrol_aerial_won', 'off_camera', 'out',
       'pass_aerial_won', 'pass_angle', 'pass_assisted_shot_id',
       'pass_body_part', 'pass_cross', 'pass_deflected', 'pass_end_location',
       'pass_height', 'pass_inswinging', 'pass_length', 'pass_outcome',
       'pass_outswinging', 'pass_recipient', 'pass_shot_assist',
       'pass_straight', 'pass_switch', 'pass_technique', 'pass_through_ball',
       'pass_type', 'period', 'play_pattern', 'player', 'player_id',
       'position', 'possession', 'possession_team', 'possession_team_id',
       'related_events', 'second', 'shot_aerial_won', 'shot_body_part',
       'shot_end_location', 'shot_first_time', 'shot_freeze_frame',
       'shot_key_pass_id', 'shot_one_on_one', 'shot_outcome',
       'shot_statsbomb_xg', 'shot_technique', 'shot_type',
       'substitution_outcome', 'substitution_replacement', 'tactics', 'team',
       'team_id', 'timestamp', 'type', 'under_pressure'],
      dtype='object')

In [61]:
events=events[['team', 'type', 'minute', 'location', 'pass_end_location', 'player']]
events=events[events['team']=='Manchester United'].reset_index()

In [62]:
events.head(20)

,index,team,type,minute,location,pass_end_location,player
0,1,Manchester United,Starting XI,0,NaN,NaN,NaN
1,2,Manchester United,Half Start,0,NaN,NaN,NaN
2,4,Manchester United,Half Start,45,NaN,NaN,NaN
3,11,Manchester United,Pass,0,"[6.0, 36.0]","[8.2, 13.8]",David de Gea Quintana
4,12,Manchester United,Pass,0,"[47.7, 19.1]","[36.6, 38.5]",Daley Blind
5,13,Manchester United,Pass,0,"[36.6, 40.2]","[33.6, 17.4]",Morgan Schneiderlin
6,14,Manchester United,Pass,1,"[27.8, 20.6]","[4.3, 41.3]",Daley Blind
7,15,Manchester United,Pass,1,"[7.2, 44.9]","[68.5, 16.2]",David de Gea Quintana
8,17,Manchester United,Pass,1,"[65.4, 18.1]","[77.8, 33.6]",Marouane Fellaini-Bakkioui
9,23,Manchester United,Pass,1,"[9.4, 22.0]","[25.6, 17.4]",David de Gea Quintana
10,24,Manchester United,Pass,1,"[29.7, 17.8]","[32.5, 40.4]",Daley Blind
11,25,Manchester United,Pass,1,"[34.8, 41.6]","[34.1, 19.2]",Morgan Schneiderlin
12,26,Manchester United,Pass,1,"[42.2, 15.5]","[34.1, 35.7]",Daley Blind
13,27,Manchester United,Pass,1,"[35.9, 38.5]","[38.7, 68.1]",Morgan Schneiderlin
14,28,Manchester United,Pass,1,"[41.0, 67.3]","[79.6, 0.7]",Chris Smalling
15,29,Manchester United,Pass,1,"[79.6, 1.0]","[90.6, 0.3]",Anthony Martial
16,32,Manchester United,Pass,2,"[39.8, 13.7]","[4.6, 35.7]",Daley Blind
17,33,Manchester United,Pass,2,"[7.8, 42.8]","[68.6, 5.8]",David de Gea Quintana
18,34,Manchester United,Pass,2,"[75.5, 0.6]","[71.9, 4.9]",Marouane Fellaini-Bakkioui
19,36,Manchester United,Pass,2,"[52.4, 7.6]","[43.6, 13.0]",Matteo Darmian